version: "3"

services:
  signlink-db:
    image: postgres:16.3
    restart: always
    volumes:
      - ./signlink-db/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=signlink

  backend-signlink:
    build: ./backend_web
    volumes:
      - ./backend_web/src:/app/src
    ports:
      - 4001:4001
    command: npm run start:dev
    environment:
      - PORT=4001
      - SERVER_URL=http://localhost:4001
      - PREFIX=/backend_signlink/api
      - EMAIL=fbonillamontalvo@gmail.com
      - PASS_EMAIL=lcwp ojvl mdwl yjvp
      - DB_HOST=signlink-db
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=signlink
      - DB_PORT=5432
      - TYPE=service_account
      - PROJECT_ID=signlink-mvp
      - PRIVATE_KEY_ID=1c4e701d63e3dda1a8573003959f054c28adb4b7
      - PRIVATE_KEY="secret/key.txt"
      - CLIENT_EMAIL=firebase-adminsdk-fbsvc@signlink-mvp.iam.gserviceaccount.com
      - CLIENT_ID=107727872217143916440v
      - AUTH_URI=https://accounts.google.com/o/oauth2/auth
      - TOKEN_URI=https://oauth2.googleapis.com/token
      - AUTH_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - CLIENT_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40signlink-mvp.iam.gserviceaccount.com
      - UNIVERSAL_DOMAIN=googleapis.com
      - JWT_SECRET="Cc7OpmPHZYpynkXR92aL0LvRwL50CMkWY4mjCZ9742lLGY3GKnKhOe959jiypn1y4k+I04gBISP4kcU4yF4Lu5UCuaGahH2S54KOAQ4XF97FqRkzxZmJrTzsQyVBRuqwSU3QN7R+r7xA8OXr3vv5PUfXBMul42PPoP6gegbOrOTWo6OrhjWTRoFuktIj8YdFC2Tldh3yScgbi1sDY+eX4AHj8/FYtN6GxbZhNfahipG2KGHFzIJ6w2no41v3bngDRyrqpUDaR4Q5Mzqj5eL5zpt+hl/bR3l65FSuavf7gkfVc4AKO6au8z/Wom4CDR7HDf4YYbfestLu9y2Hxwrzqg=="
    depends_on:
      - signlink-db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - 4040:80
    depends_on:
      - signlink-db
